baseurl: https://rdev.pages.dev/
defaultContentLanguage: en
languages:
  en:
    weight: 1
    title: Ramon Dev's blog
  fr:
    title: Le blogue de Ramon Dev
    weight: 2
theme: hugo-uncaged
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: Blue Sky
      url: https://bsky.app/profile/rdev0x1.bsky.social
params:
  description: Yet another geek blog.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.jpg
    width: 50
  utterances:
    repo: "rdev0x1/rdev-blog-comments"
    issueTerm: "pathname"
    theme: "github-light"
    crossorigin: "anonymous"
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
log:
  level: debug
